FROM python:3.12-slim

WORKDIR /mlflow

COPY requirements-mlflow.txt .

RUN pip install --no-cache-dir -r requirements-mlflow.txt

RUN useradd --create-home --uid 1000 --shell /usr/sbin/nologin mlflowuser

USER mlflowuser

EXPOSE 5000